source 'https://rubygems.org'

gem 'rails'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
end
  
gem 'sass-rails'
gem 'coffee-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'execjs'
gem 'therubyracer', :platforms => :ruby

gem 'uglifier'

gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
gem 'jquery-datatables-tabletools-rails', github: 'kindjal/jquery-datatables-tabletools-rails'
gem 'jquery-ui-rails', github: 'wiwie/jquery-ui-rails'

gem 'jquery-rails'

gem 'simple-navigation'
gem 'authlogic', github: 'wiwie/authlogic'
gem 'rails3-generators'
gem 'json'
gem 'raphael-rails'
gem 'cells'
gem "cells-erb"
gem 'dynamic_form'
gem 'immigrant' # allows recreation of existing foreign keys in the database into the migration files
#gem 'rails_sql_views', github: 'centresource/rails_sql_views' # supports view
gem 'mathjax-rails'
gem 'composite_primary_keys'

gem "twitter-bootstrap-rails", github: 'wiwie/twitter-bootstrap-rails'

# sitemap creation
gem 'sitemap_generator'

# compatibility with our rails 3 models with rails 4
gem 'protected_attributes'